"""describe-change

Revision ID: 1b476c0fb4ec
Revises: 5b7ac32d9809
Create Date: 2026-01-05 17:30:58.276195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b476c0fb4ec'
down_revision = '5b7ac32d9809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cfg_system_batch',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('record_per_job', sa.BigInteger(), nullable=True),
    sa.Column('system_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_cfg_system_batch')
    # ### end Alembic commands ###
