"""Initated the migration

Revision ID: 1f8c06e09913
Revises: 9492ca663f2b
Create Date: 2026-01-03 10:47:03.853770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f8c06e09913'
down_revision = '9492ca663f2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
