"""add table tbl_txn_transactions

Revision ID: 5b5d19f77195
Revises: 2600a4e137a3
Create Date: 2026-01-10 16:13:16.930678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5b5d19f77195'
down_revision = '2600a4e137a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_txn_manual')
    op.drop_table('tbl_cfg_general_ledger')
    op.drop_table('tbl_txn_journal_entries')
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'conditions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'tolerance',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_channel_id'), 'tbl_cfg_matching_rule', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_rule_name'), 'tbl_cfg_matching_rule', ['rule_name'], unique=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_status'), 'tbl_cfg_matching_rule', ['status'], unique=False)
    op.add_column('tbl_txn_transactions', sa.Column('otherDetails', sa.Text(), nullable=True))
    op.create_index(op.f('ix_tbl_txn_transactions_txn_id'), 'tbl_txn_transactions', ['txn_id'], unique=False)
    op.drop_column('tbl_txn_transactions', 'other_details')
    op.add_column('tbl_upload_files', sa.Column('total_records', sa.BigInteger(), nullable=True, comment='Total records in uploaded file'))
    op.add_column('tbl_upload_files', sa.Column('processed_records', sa.BigInteger(), nullable=True, comment='Number of records processed so far'))
    op.add_column('tbl_upload_files', sa.Column('success_records', sa.BigInteger(), nullable=True, comment='Number of successfully inserted records'))
    op.add_column('tbl_upload_files', sa.Column('failed_records', sa.BigInteger(), nullable=True, comment='Number of failed records'))
    op.add_column('tbl_upload_files', sa.Column('duplicate_records', sa.BigInteger(), nullable=True, comment='Number of duplicate records skipped'))
    op.add_column('tbl_upload_files', sa.Column('progress_percentage', sa.Float(), nullable=True, comment='Upload progress (0-100)'))
    op.add_column('tbl_upload_files', sa.Column('upload_started_at', sa.TIMESTAMP(), nullable=True, comment='When upload processing started'))
    op.add_column('tbl_upload_files', sa.Column('upload_completed_at', sa.TIMESTAMP(), nullable=True, comment='When upload processing completed'))
    op.add_column('tbl_upload_files', sa.Column('processing_time_seconds', sa.Integer(), nullable=True, comment='Total processing time in seconds'))
    op.add_column('tbl_upload_files', sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if upload failed'))
    op.add_column('tbl_upload_files', sa.Column('error_details', sa.Text(), nullable=True, comment='Detailed error information (JSON format)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_upload_files', 'error_details')
    op.drop_column('tbl_upload_files', 'error_message')
    op.drop_column('tbl_upload_files', 'processing_time_seconds')
    op.drop_column('tbl_upload_files', 'upload_completed_at')
    op.drop_column('tbl_upload_files', 'upload_started_at')
    op.drop_column('tbl_upload_files', 'progress_percentage')
    op.drop_column('tbl_upload_files', 'duplicate_records')
    op.drop_column('tbl_upload_files', 'failed_records')
    op.drop_column('tbl_upload_files', 'success_records')
    op.drop_column('tbl_upload_files', 'processed_records')
    op.drop_column('tbl_upload_files', 'total_records')
    op.add_column('tbl_txn_transactions', sa.Column('other_details', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_tbl_txn_transactions_txn_id'), table_name='tbl_txn_transactions')
    op.drop_column('tbl_txn_transactions', 'otherDetails')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_status'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_rule_name'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_channel_id'), table_name='tbl_cfg_matching_rule')
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'tolerance',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'conditions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_table('tbl_txn_journal_entries',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('recon_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_brn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cif', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('drcr_ind', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('ccy', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('exch_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fcy_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lcy_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trn_dt', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('post_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('post_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('batch_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auth_stat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('maker_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('maker_dt_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checker_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('checker_dt_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_txn_journal_entries_pkey'))
    )
    op.create_table('tbl_cfg_general_ledger',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('general_ledger', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gl_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('apply_to_all_channels', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gl_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_cfg_general_ledger_pkey'))
    )
    op.create_table('tbl_txn_manual',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('manual_txn_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recon_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('txn_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cif', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ccy', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('json_file', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('file_transactions_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reconciled_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reconciled_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_journal_entry', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('journal_entry_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], name=op.f('fk_manual_channel')),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_created_by')),
    sa.ForeignKeyConstraint(['file_transactions_id'], ['tbl_upload_files.id'], name=op.f('fk_manual_file')),
    sa.ForeignKeyConstraint(['reconciled_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_reconciled_by')),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_cfg_source.id'], name=op.f('fk_manual_source')),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_txn_manual_pkey'))
    )
    # ### end Alembic commands ###
