"""update matching rule model with json and indexes

Revision ID: 69bf686c3553
Revises: 1f8c06e09913
Create Date: 2026-01-05 11:01:06.438012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69bf686c3553'
down_revision = '1f8c06e09913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    
    # Convert TEXT to JSON with USING clause for conditions
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN conditions TYPE JSON 
        USING CASE 
            WHEN conditions IS NULL OR conditions::text = '' THEN NULL
            ELSE conditions::json
        END
    """)
    
    # Convert TEXT to JSON with USING clause for tolerance
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN tolerance TYPE JSON 
        USING CASE 
            WHEN tolerance IS NULL OR tolerance::text = '' THEN NULL
            ELSE tolerance::json
        END
    """)
    
    # Fill NULL values before making columns NOT NULL
    op.execute("""
        UPDATE tbl_cfg_matching_rule
        SET created_at = NOW()
        WHERE created_at IS NULL
    """)
    
    op.execute("""
        UPDATE tbl_cfg_matching_rule
        SET updated_at = NOW()
        WHERE updated_at IS NULL
    """)
    
    op.execute("""
        UPDATE tbl_cfg_matching_rule
        SET version_number = 1
        WHERE version_number IS NULL
    """)
    
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    
    # Create indexes only if they don't exist
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_tbl_cfg_matching_rule_channel_id 
        ON tbl_cfg_matching_rule (channel_id)
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_tbl_cfg_matching_rule_rule_name 
        ON tbl_cfg_matching_rule (rule_name)
    """)
    
    op.execute("""
        CREATE INDEX IF NOT EXISTS ix_tbl_cfg_matching_rule_status 
        ON tbl_cfg_matching_rule (status)
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_status'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_rule_name'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_channel_id'), table_name='tbl_cfg_matching_rule')
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Convert JSON back to TEXT for tolerance
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN tolerance TYPE TEXT 
        USING tolerance::text
    """)
    
    # Convert JSON back to TEXT for conditions
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN conditions TYPE TEXT 
        USING conditions::text
    """)
    
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
