"""update matching rule model with json and indexes

Revision ID: 69bf686c3553
Revises: 1f8c06e09913
Create Date: 2026-01-05 11:01:06.438012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69bf686c3553'
down_revision = '1f8c06e09913'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    
    # Convert TEXT to JSON with USING clause for conditions
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN conditions TYPE JSON 
        USING CASE 
            WHEN conditions IS NULL OR conditions = '' THEN NULL
            ELSE conditions::json
        END
    """)
    
    # Convert TEXT to JSON with USING clause for tolerance
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN tolerance TYPE JSON 
        USING CASE 
            WHEN tolerance IS NULL OR tolerance = '' THEN NULL
            ELSE tolerance::json
        END
    """)
    
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_channel_id'), 'tbl_cfg_matching_rule', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_rule_name'), 'tbl_cfg_matching_rule', ['rule_name'], unique=False)
    op.create_index(op.f('ix_tbl_cfg_matching_rule_status'), 'tbl_cfg_matching_rule', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_status'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_rule_name'), table_name='tbl_cfg_matching_rule')
    op.drop_index(op.f('ix_tbl_cfg_matching_rule_channel_id'), table_name='tbl_cfg_matching_rule')
    op.alter_column('tbl_cfg_matching_rule', 'version_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    
    # Convert JSON back to TEXT for tolerance
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN tolerance TYPE TEXT 
        USING tolerance::text
    """)
    
    # Convert JSON back to TEXT for conditions
    op.execute("""
        ALTER TABLE tbl_cfg_matching_rule 
        ALTER COLUMN conditions TYPE TEXT 
        USING conditions::text
    """)
    
    op.alter_column('tbl_cfg_matching_rule', 'channel_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('tbl_cfg_matching_rule', 'rule_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
