"""Add network table

Revision ID: 72fa8e9b5a6e
Revises: 3880782acd21
Create Date: 2026-01-20 15:09:15.529368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '72fa8e9b5a6e'
down_revision = '3880782acd21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cfg_networks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('network_name', sa.String(length=255), nullable=False),
    sa.Column('network_desc', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tbl_cfg_networks_channel_id'), 'tbl_cfg_networks', ['channel_id'], unique=False)
    op.create_index(op.f('ix_tbl_cfg_networks_network_name'), 'tbl_cfg_networks', ['network_name'], unique=True)
    op.create_index(op.f('ix_tbl_cfg_networks_status'), 'tbl_cfg_networks', ['status'], unique=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_tbl_cfg_networks_status'), table_name='tbl_cfg_networks')
    op.drop_index(op.f('ix_tbl_cfg_networks_network_name'), table_name='tbl_cfg_networks')
    op.drop_index(op.f('ix_tbl_cfg_networks_channel_id'), table_name='tbl_cfg_networks')
    op.drop_table('tbl_cfg_networks')
    # ### end Alembic commands ###
