"""describe-change

Revision ID: 7f3f94d03de2
Revises: 3ee79a867077
Create Date: 2025-12-30 11:28:04.886975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3f94d03de2'
down_revision = '3ee79a867077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_cfg_module',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_name', sa.String(length=255), nullable=True),
    sa.Column('module_description', sa.Text(), nullable=True),
    sa.Column('module_permission_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_source',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_type', sa.Integer(), nullable=True),
    sa.Column('source_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permission_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['tbl_cfg_module.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('f_name', sa.String(length=100), nullable=True),
    sa.Column('m_name', sa.String(length=100), nullable=True),
    sa.Column('l_name', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['role'], ['tbl_cfg_roles.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_name', sa.String(length=255), nullable=True),
    sa.Column('channel_description', sa.Text(), nullable=True),
    sa.Column('cannel_source_id', sa.BigInteger(), nullable=True),
    sa.Column('network_source_id', sa.BigInteger(), nullable=True),
    sa.Column('cbs_source_id', sa.BigInteger(), nullable=True),
    sa.Column('switch_source_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cannel_source_id'], ['tbl_cfg_source.id'], ),
    sa.ForeignKeyConstraint(['cbs_source_id'], ['tbl_cfg_source.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['network_source_id'], ['tbl_cfg_source.id'], ),
    sa.ForeignKeyConstraint(['switch_source_id'], ['tbl_cfg_source.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_logs_audit',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_type', sa.String(length=255), nullable=True),
    sa.Column('log_details', sa.Text(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_logs_system',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('log_type', sa.String(length=255), nullable=True),
    sa.Column('log_details', sa.Text(), nullable=True),
    sa.Column('added_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_matching_rule',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('rule_name', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('rule_desc', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('tolerance', sa.Text(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_upload_api',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('api_name', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('responce_formate', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=True),
    sa.Column('auth_token', sa.Text(), nullable=True),
    sa.Column('api_time_out', sa.String(length=50), nullable=True),
    sa.Column('max_try', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_cfg_upload_schedulars',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('schedular_name', sa.String(length=255), nullable=True),
    sa.Column('schedular_time', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_upload_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_details', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('record_details', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_txn_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('recon_reference_number', sa.String(length=255), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('source_id', sa.BigInteger(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('source_reference_number', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.String(length=50), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('account_number', sa.String(length=50), nullable=True),
    sa.Column('ccy', sa.String(length=10), nullable=True),
    sa.Column('otherDetails', sa.Text(), nullable=True),
    sa.Column('file_transactions_id', sa.BigInteger(), nullable=True),
    sa.Column('reconciled_status', sa.Boolean(), nullable=True),
    sa.Column('reconciled_mode', sa.Boolean(), nullable=True),
    sa.Column('reconciled_by', sa.BigInteger(), nullable=True),
    sa.Column('match_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('match_conditon', sa.Text(), nullable=True),
    sa.Column('match_status', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['file_transactions_id'], ['tbl_upload_files.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by'], ['tbl_cfg_users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_cfg_source.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_txn_transactions')
    op.drop_table('tbl_upload_files')
    op.drop_table('tbl_cfg_upload_schedulars')
    op.drop_table('tbl_cfg_upload_api')
    op.drop_table('tbl_cfg_matching_rule')
    op.drop_table('tbl_logs_system')
    op.drop_table('tbl_logs_audit')
    op.drop_table('tbl_cfg_channels')
    op.drop_table('tbl_cfg_users')
    op.drop_table('tbl_cfg_roles')
    op.drop_table('tbl_cfg_source')
    op.drop_table('tbl_cfg_module')
    # ### end Alembic commands ###
