"""describe-change

Revision ID: 9492ca663f2b
Revises: 7f3f94d03de2
Create Date: 2026-01-02 10:15:49.611549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9492ca663f2b'
down_revision = '7f3f94d03de2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_cfg_module', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('tbl_cfg_module', 'update_at')
    op.add_column('tbl_cfg_roles', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('tbl_cfg_roles', 'update_at')
    op.add_column('tbl_upload_files', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_upload_files', 'updated_at')
    op.add_column('tbl_cfg_roles', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tbl_cfg_roles', 'updated_at')
    op.add_column('tbl_cfg_module', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('tbl_cfg_module', 'updated_at')
    # ### end Alembic commands ###
