"""describe-change

Revision ID: f03367e1c860
Revises: 1e7d5bf98103
Create Date: 2026-01-14 11:26:53.018590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f03367e1c860'
down_revision = '1e7d5bf98103'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_cfg_general_ledger')
    op.drop_table('tbl_txn_journal_entries')
    op.drop_table('tbl_txn_manual')
    op.drop_index(op.f('idx_txn_channel_source'), table_name='tbl_txn_transactions')
    op.drop_index(op.f('idx_txn_created_at'), table_name='tbl_txn_transactions')
    op.drop_index(op.f('idx_txn_date'), table_name='tbl_txn_transactions')
    op.drop_index(op.f('idx_txn_duplicate_check'), table_name='tbl_txn_transactions', postgresql_where='((match_status IS NULL) OR (match_status = 0))')
    op.drop_index(op.f('idx_txn_file_id'), table_name='tbl_txn_transactions')
    op.drop_index(op.f('idx_upload_file_channel'), table_name='tbl_upload_files')
    op.drop_index(op.f('idx_upload_file_status'), table_name='tbl_upload_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_upload_file_status'), 'tbl_upload_files', ['status'], unique=False)
    op.create_index(op.f('idx_upload_file_channel'), 'tbl_upload_files', ['channel_id'], unique=False)
    op.create_index(op.f('idx_txn_file_id'), 'tbl_txn_transactions', ['file_transactions_id'], unique=False)
    op.create_index(op.f('idx_txn_duplicate_check'), 'tbl_txn_transactions', ['channel_id', 'source_id', 'amount', 'date'], unique=False, postgresql_where='((match_status IS NULL) OR (match_status = 0))')
    op.create_index(op.f('idx_txn_date'), 'tbl_txn_transactions', ['date'], unique=False)
    op.create_index(op.f('idx_txn_created_at'), 'tbl_txn_transactions', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_txn_channel_source'), 'tbl_txn_transactions', ['channel_id', 'source_id'], unique=False)
    op.create_table('tbl_txn_manual',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('manual_txn_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('recon_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reference_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('txn_date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('cif', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ccy', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('json_file', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('file_transactions_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('reconciled_status', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reconciled_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_journal_entry', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('journal_entry_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['tbl_cfg_channels.id'], name=op.f('fk_manual_channel')),
    sa.ForeignKeyConstraint(['created_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_created_by')),
    sa.ForeignKeyConstraint(['file_transactions_id'], ['tbl_upload_files.id'], name=op.f('fk_manual_file')),
    sa.ForeignKeyConstraint(['reconciled_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_reconciled_by')),
    sa.ForeignKeyConstraint(['source_id'], ['tbl_cfg_source.id'], name=op.f('fk_manual_source')),
    sa.ForeignKeyConstraint(['updated_by'], ['tbl_cfg_users.id'], name=op.f('fk_manual_updated_by')),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_txn_manual_pkey'))
    )
    op.create_table('tbl_txn_journal_entries',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('recon_reference_number', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_brn', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_desc', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cif', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('drcr_ind', sa.CHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('ccy', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('exch_rate', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fcy_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('lcy_amount', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trn_dt', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('post_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('post_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('batch_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('source_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('auth_stat', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('maker_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('maker_dt_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('checker_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('checker_dt_stamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_txn_journal_entries_pkey'))
    )
    op.create_table('tbl_cfg_general_ledger',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('general_ledger', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('gl_role', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('channel_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('apply_to_all_channels', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('gl_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tbl_cfg_general_ledger_pkey'))
    )
    # ### end Alembic commands ###
